### PR TITLE
113 wrong name of method for checking threadmessagedeletedevent

### LINKED ISSUE #113: Wrong name of method for checking ThreadMessageDeletedEvent
The method `isThreadDeletedMessageEvent` should be deprecated in favour of new `isThreadMessageDeletedEvent` method.

## Steps:
- Deprecate `isThreadDeletedMessageEvent`
- Add `isThreadMessageDeletedEvent`

### PR DESCRIPTION
**Pull request by Uriagat**
Closes #113

### CODE REVIEW

File: endpoint/thread/src/Events.cpp [hunk 1]
```diff
@@ -180,6 +180,10 @@ bool Events::isThreadDeletedMessageEvent(const core::EventHolder& handler) {
     return handler.type() == "threadMessageDeleted";
```
Comment (kisielewski) [inline endpoint/thread/src/Events.cpp:180]:
```suggestion
    return isThreadMessageDeletedEvent(handler);
```

**Review by kisielewski — CHANGES_REQUESTED** [review]

**Review by zurekz — APPROVED** [review]

**Review by kisielewski — APPROVED** [review]
