### PR TITLE
232 bug when calling methods on extkey returned from frombase58

### LINKED ISSUE #232: [BUG]: when calling methods on ExtKey returned from fromBase58
## Code to reproduce

```cpp
        auto extKeyRandom = privmx::endpoint::crypto::ExtKey::generateRandom();
        auto publicPartAsBase58 = extKeyRandom.getPublicPartAsBase58();
        auto extKey = privmx::endpoint::crypto::ExtKey::fromBase58(publicPartAsBase58);
        extKey.derive(4);     
        extKey.deriveHardened(4);
        extKey.getPrivatePartAsBase58();
        extKey.getPrivateKey();
        extKey.getPrivateEncKey();
```

## Description

When an extKey object is created by `ExtKey::fromBase58` method using public key in  Base58 as an argument, the following issues occur:

1. Calling `derive` or `deriveHardened` methods on this object throw `std::exception` with message `Crypto exception: Derive from public key not implemented`
   This exception is thrown directly from the c++ code - in **privmx/crypto**.
   The library should throw \`PrivmxException\`

2. When calling "private" methods such as `getPrivatePartAsBase58`, `getPrivateKey`, `getPrivateEncKey` on this object - the library crashes with `SIGSEGV`.

   getPrivatePartAsBase58
   getPrivateKey
   getPrivateEncKey

   Instead of a crash, the library should throw \`PrivmxException\`

### PR DESCRIPTION
**Pull request by Uriagat**
Closes #232

### CODE REVIEW

File: crypto/base/include/privmx/crypto/ecc/ExtKey.hpp [hunk 1]
```diff
@@ -78,6 +79,7 @@ inline std::string ExtKey::getPublicPartAsBase58() const {
 }
 
 inline PrivateKey ExtKey::getPrivateKey() const {
+    if (!_is_private) {throw DeriveFromPublicKeyNotImplementedException();}
```
Comment (zurekz) [inline crypto/base/include/privmx/crypto/ecc/ExtKey.hpp:82]: why inline?

File: crypto/base/include/privmx/crypto/ecc/ExtKey.hpp [hunk 2]
```diff
@@ -86,6 +88,7 @@ inline PublicKey ExtKey::getPublicKey() const {
 }
 
 inline std::string ExtKey::getPrivateEncKey() const {
+    if (!_is_private) {throw DeriveFromPublicKeyNotImplementedException();}
```
Comment (zurekz) [inline crypto/base/include/privmx/crypto/ecc/ExtKey.hpp:91]: why inline?

**Review by zurekz — CHANGES_REQUESTED** [review]

File: crypto/base/include/privmx/crypto/ecc/ExtKey.hpp [hunk 3]
```diff
@@ -78,6 +79,9 @@ inline std::string ExtKey::getPublicPartAsBase58() const {
 }
 
 inline PrivateKey ExtKey::getPrivateKey() const {
+    if (!_is_private) {
+        throw DeriveFromPublicKeyNotImplementedException();
```
Comment (kisielewski) [inline crypto/base/include/privmx/crypto/ecc/ExtKey.hpp:83]: Change exception name for all methods, e.g.:
```suggestion
        throw ExtKeyDoesNotHoldPrivateKeyException();
```

**Review by kisielewski — CHANGES_REQUESTED** [review]

**Review by zurekz — APPROVED** [review]
